FROM node:24-alpine

WORKDIR /opt/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Set permissions
RUN chown -R node:node /opt/app

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]