services:
  postgres:
    image: postgres:14-alpine
    container_name: polaris_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: polaris_youth_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Standard PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - polaris_network

  strapi:
    build:
      context: ./cms
      dockerfile: Dockerfile.dev
    container_name: polaris_cms
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=polaris_youth_dev
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=toBeModified1,toBeModified2,toBeModified3,toBeModified4
      - API_TOKEN_SALT=toBeModifiedApiTokenSalt
      - ADMIN_JWT_SECRET=toBeModifiedAdminJwtSecret
      - TRANSFER_TOKEN_SALT=toBeModifiedTransferTokenSalt
      - JWT_SECRET=toBeModifiedJwtSecret
    ports:
      - "1337:1337"
    volumes:
      - ./cms:/opt/app
      - /opt/app/node_modules
      - strapi_uploads:/opt/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - polaris_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polaris_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://localhost:1337
      - NEXT_PUBLIC_STRAPI_API_URL=http://localhost:1337/api
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    depends_on:
      - strapi
    networks:
      - polaris_network

volumes:
  postgres_data:
  strapi_uploads:

networks:
  polaris_network:
    driver: bridge